### ISSUE TITLE
optional arrays can cause "null cannot be cast to non-null type" Exceptions

### ISSUE THREAD

**Issue by thedanielhanke** [pwall567/json-kotlin-schema-codegen#47]
Hi,

optional arrays ( marked them explicitly as `"optional": true` + empty `required` ) inside of an object, e.g:

```json
  "type": "object",
  "required": [],
  "properties": {
    "components": {
      "optional": true,
      "description": "A list to define components",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Component"
      }
    },
```

will result in generated code such as:

```kt
class Schema(
    private val cg_map: Map<String, Any?>
) : Map<String, Any?> by cg_map {

    init {
        if (cg_map.containsKey("components"))
            require(cg_map["components"] is List<*>) { "components is not the correct type, expecting List<Component>?" }
            (cg_map["components"] as List<*>).forEach { cg_0 ->
                require(cg_0 is Component) { "components item is not the correct type, expecting Component" }
            }
```

which will lead to to 

```
Error deserializing i...generated.Schema - null cannot be cast to non-null type kotlin.collections.List<*>
io.kjson.JSONKotlinException: Error deserializing i...generated.Schema - null cannot be cast to non-null type kotlin.collections.List<*>
	at io.kjson.JSONKotlinException$Companion.fatal(JSONKotlinException.kt:79)
	at io.kjson.JSONKotlinException$Companion.fatal$default(JSONKotlinException.kt:78)
	at io.kjson.JSONDeserializer.deserialize$kjson(JSONDeserializer.kt:230)
	at io.kjson.JSONDeserializer.deserialize(JSONDeserializer.kt:134)
	at io.kjson.JSONFunKt.parseJSON(JSONFun.kt:56)
```

if the key `components` is missing in json

whereas using safe casting does not. (`(cg_map["components"] as? List<*>)?.forEach { cg_0 ->`)

is this my bad or a bug?

TY.

versions 
```
implementation("net.pwall.json:json-kotlin-schema:0.48")
implementation("net.pwall.json:json-kotlin-schema-codegen:0.108")
implementation("io.kjson:kjson:8.0")
```

config: 
```
{
  "packageName": "schema.generated",
  "additionalPropertiesOption": "strict",
  "nestedClassNameOption": "refSchema"
}

```

**Comment by pwall567** [comment]
I won't be able to look into reproducing this issue for a day or two, but a couple of points stand out immediately:
- version 0.108 of `json-kotlin-schema-codegen` requires version 0.48 of `json-kotlin-schema`; version 0.49 uses a different underlying JSON library and `json-kotlin-schema-codegen` has not yet been updated to use the same library (I'm surprised it even works!)
- you don't show your config file, but it appears from the generated code that you are using `additionalPropertiesOption: strict` – if you do not need this option, the generated code will be much clearer without it (see [additionalProperties and patternProperties](https://github.com/pwall567/json-kotlin-schema-codegen/blob/main/PROPERTIES.md) for more details) and the bug (if it is a bug) may not be present in the simpler case
- that stack trace should have had a "Caused by" – it would be good to see that information, as well as the full generated code (although I plan to try to reproduce the issue when I get the time)
- there is no "optional" keyword in JSON Schema (it was in a very early version, but it was removed long ago); the fact that the property name is not in a `required` array is sufficient for it to be considered optional

**Comment by thedanielhanke** [comment]
Hey Peter,

> version 0.108 of json-kotlin-schema-codegen requires version 0.48 of json-kotlin-schema; version 0.49 uses a different underlying JSON library and json-kotlin-schema-codegen has not yet been updated to use the same library (I'm surprised it even works!)

Both Versions specified in build.gradle.kts lead to the same result. but thanks that info ;)


> you don't show your config file 

added it to the issue. strict mode is required in our case.


> that stack trace should have had a "Caused by" – it would be good to see that information, as well as the full generated code (although I plan to try to reproduce the issue when I get the time)

```
Error deserializing .model.schema.generated.Schema - null cannot be cast to non-null type kotlin.collections.List<*>
io.kjson.JSONKotlinException: Error deserializing .model.schema.generated.Schema - null cannot be cast to non-null type kotlin.collections.List<*>
	at io.kjson.JSONKotlinException$Companion.fatal(JSONKotlinException.kt:79)
	at io.kjson.JSONKotlinException$Companion.fatal$default(JSONKotlinException.kt:78)
	at io.kjson.JSONDeserializer.deserialize$kjson(JSONDeserializer.kt:230)
	at io.kjson.JSONDeserializer.deserialize(JSONDeserializer.kt:134)
	at io.kjson.JSONFunKt.parseJSON(JSONFun.kt:56)
	at .model.schema.FileSystemSchemaLoader.load(FileSystemSchemaLoader.kt:43)
	at .PluginSpec$1$1.invokeSuspend(PluginSpec.kt:10)
	at .PluginSpec$1$1.invoke(PluginSpec.kt)
	at .PluginSpec$1$1.invoke(PluginSpec.kt)
	at io.kotest.core.spec.style.scopes.RootScopeKt$addTest$1.invokeSuspend(RootScope.kt:36)
	at io.kotest.core.spec.style.scopes.RootScopeKt$addTest$1.invoke(RootScope.kt)
	at io.kotest.core.spec.style.scopes.RootScopeKt$addTest$1.invoke(RootScope.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$innerExecute$1.invokeSuspend(TestCaseExecutor.kt:91)
	at io.kotest.engine.test.TestCaseExecutor$execute$innerExecute$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$innerExecute$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.CoroutineDebugProbeInterceptor.intercept(CoroutineDebugProbeInterceptor.kt:29)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestInvocationInterceptor$runBeforeTestAfter$executeWithBeforeAfter$1.invokeSuspend(TestInvocationInterceptor.kt:63)
	at io.kotest.engine.test.TestInvocationInterceptor$runBeforeTestAfter$executeWithBeforeAfter$1.invoke(TestInvocationInterceptor.kt)
	at io.kotest.engine.test.TestInvocationInterceptor$runBeforeTestAfter$executeWithBeforeAfter$1.invoke(TestInvocationInterceptor.kt)
	at io.kotest.engine.test.interceptors.InvocationTimeoutInterceptor$intercept$3.invokeSuspend(InvocationTimeoutInterceptor.kt:43)
	at io.kotest.engine.test.interceptors.InvocationTimeoutInterceptor$intercept$3.invoke(InvocationTimeoutInterceptor.kt)
	at io.kotest.engine.test.interceptors.InvocationTimeoutInterceptor$intercept$3.invoke(InvocationTimeoutInterceptor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:72)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:104)
	at io.kotest.engine.test.interceptors.InvocationTimeoutInterceptor.intercept(InvocationTimeoutInterceptor.kt:42)
	at io.kotest.engine.test.TestInvocationInterceptor$runBeforeTestAfter$wrappedTest$1$1.invokeSuspend(TestInvocationInterceptor.kt:70)
	at io.kotest.engine.test.TestInvocationInterceptor$runBeforeTestAfter$wrappedTest$1$1.invoke(TestInvocationInterceptor.kt)
	at io.kotest.engine.test.TestInvocationInterceptor$runBeforeTestAfter$wrappedTest$1$1.invoke(TestInvocationInterceptor.kt)
	at io.kotest.engine.test.TestInvocationInterceptor.runBeforeTestAfter(TestInvocationInterceptor.kt:73)
	at io.kotest.engine.test.TestInvocationInterceptor.access$runBeforeTestAfter(TestInvocationInterceptor.kt:14)
	at io.kotest.engine.test.TestInvocationInterceptor$intercept$2$1.invokeSuspend(TestInvocationInterceptor.kt:36)
	at io.kotest.engine.test.TestInvocationInterceptor$intercept$2$1.invoke(TestInvocationInterceptor.kt)
	at io.kotest.engine.test.TestInvocationInterceptor$intercept$2$1.invoke(TestInvocationInterceptor.kt)
	at io.kotest.mpp.ReplayKt.replay(replay.kt:15)
	at io.kotest.engine.test.TestInvocationInterceptor$intercept$2.invokeSuspend(TestInvocationInterceptor.kt:32)
	at io.kotest.engine.test.TestInvocationInterceptor$intercept$2.invoke(TestInvocationInterceptor.kt)
	at io.kotest.engine.test.TestInvocationInterceptor$intercept$2.invoke(TestInvocationInterceptor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at io.kotest.engine.test.TestInvocationInterceptor.intercept(TestInvocationInterceptor.kt:31)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.interceptors.MarkAbortedExceptionsAsSkippedTestInterceptor.intercept(MarkAbortedExceptionsAsSkippedTestInterceptor.kt:23)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.ExpectExceptionTestInterceptor.intercept(ExpectExceptionTestInterceptor.kt:18)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.TimeoutInterceptor.intercept(TimeoutInterceptor.kt:33)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.BlockedThreadTimeoutInterceptor.intercept(BlockedThreadTimeoutInterceptor.kt:79)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.CoroutineLoggingInterceptor.intercept(CoroutineLoggingInterceptor.kt:30)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.SoftAssertInterceptor.intercept(SoftAssertInterceptor.kt:27)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.AssertionModeInterceptor.intercept(AssertionModeInterceptor.kt:25)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.LifecycleInterceptor.intercept(LifecycleInterceptor.kt:50)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.TestCaseExtensionInterceptor$intercept$2.invokeSuspend(TestCaseExtensionInterceptor.kt:24)
	at io.kotest.engine.test.interceptors.TestCaseExtensionInterceptor$intercept$2.invoke(TestCaseExtensionInterceptor.kt)
	at io.kotest.engine.test.interceptors.TestCaseExtensionInterceptor$intercept$2.invoke(TestCaseExtensionInterceptor.kt)
	at io.kotest.engine.test.TestExtensions.intercept(TestExtensions.kt:148)
	at io.kotest.engine.test.interceptors.TestCaseExtensionInterceptor.intercept(TestCaseExtensionInterceptor.kt:24)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.BeforeSpecListenerInterceptor$intercept$runTest$1$4$1.invokeSuspend(BeforeSpecListenerInterceptor.kt:50)
	at io.kotest.engine.test.interceptors.BeforeSpecListenerInterceptor$intercept$runTest$1$4$1.invoke(BeforeSpecListenerInterceptor.kt)
	at io.kotest.engine.test.interceptors.BeforeSpecListenerInterceptor$intercept$runTest$1$4$1.invoke(BeforeSpecListenerInterceptor.kt)
	at io.kotest.engine.test.interceptors.BeforeSpecListenerInterceptor.intercept(BeforeSpecListenerInterceptor.kt:60)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.TestEnabledCheckInterceptor.intercept(TestEnabledCheckInterceptor.kt:31)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.CoroutineErrorCollectorInterceptor$intercept$3.invokeSuspend(CoroutineErrorCollectorInterceptor.kt:34)
	at io.kotest.engine.test.interceptors.CoroutineErrorCollectorInterceptor$intercept$3.invoke(CoroutineErrorCollectorInterceptor.kt)
	at io.kotest.engine.test.interceptors.CoroutineErrorCollectorInterceptor$intercept$3.invoke(CoroutineErrorCollectorInterceptor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at io.kotest.engine.test.interceptors.CoroutineErrorCollectorInterceptor.intercept(CoroutineErrorCollectorInterceptor.kt:33)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.CoroutineDispatcherFactoryInterceptor$intercept$4.invokeSuspend(coroutineDispatcherFactoryInterceptor.kt:57)
	at io.kotest.engine.test.interceptors.CoroutineDispatcherFactoryInterceptor$intercept$4.invoke(coroutineDispatcherFactoryInterceptor.kt)
	at io.kotest.engine.test.interceptors.CoroutineDispatcherFactoryInterceptor$intercept$4.invoke(coroutineDispatcherFactoryInterceptor.kt)
	at io.kotest.engine.concurrency.FixedThreadCoroutineDispatcherFactory$withDispatcher$4.invokeSuspend(FixedThreadCoroutineDispatcherFactory.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<*>
	at .model.schema.generated.Schema.<init>(Schema.kt:19)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at io.kjson.JSONDeserializerFunctions.callWithSingle(JSONDeserializerFunctions.kt:194)
	at io.kjson.deserialize.DelegatingMapConstructorDeserializer.deserialize(ConstructorDeserializers.kt:249)
	at io.kjson.JSONDeserializer.deserialize$kjson(JSONDeserializer.kt:218)
	... 114 more
```

some of the relevant code parts:

schema.json:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Version": {
      "type": "integer",
      "minimum": 0
    },
    "MeasureUnit": {
      "type": "string",
      "minLength": 1
    },
    "TagTypeName": {
      "type": "string",
      "pattern": "^[A-Z0-9][A-Za-z0-9]*$"
    },
    "ComposableName": {
      "type": "string",
      "pattern": "^[A-Z0-9][A-Za-z0-9]*$"
    },
    "ComposableType": {
      "type": "string",
      "enum": [
        "COMPONENT",
        "VALUE"
      ]
    },
    "ComposableReference": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/ComposableName"
        },
        "type": {
          "$ref": "#/definitions/ComposableType"
        }
      },
      "required": ["name", "type"],
      "additionalProperties": false
    },
    "EnumValue": {
      "type": "string",
      "minLength": 1
    },
    "ValueDataType": {
      "description": "The data type of a value definition",
      "type": "string",
      "enum": [
        "BOOLEAN",
        "COMPLEX",
        "ENUM",
        "NUMBER",
        "STRING"
      ]
    },
    "ValueType": {
      "description": "A value specification is a type that gives semantic meaning to a value",
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the value type",
          "$ref": "#/definitions/ComposableName"
        },
        "description": {
          "description": "The description of the value specification",
          "type": "string"
        },
        "type": {
          "description": "The type of the value specification",
          "$ref": "#/definitions/ValueDataType"
        },
        "values": {
          "description": "A list of possible values, only applicable to the ENUM type",
          "type": "array",
          "items": {
            "$ref": "#/definitions/EnumValue"
          },
          "minItems": 1
        },
        "units": {
          "description": "An optional list of units applicable to this value specification",
          "type": "array",
          "items": {
            "$ref": "#/definitions/MeasureUnit"
          },
          "minItems": 1
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "type"
      ]
    },
    "TagDataType": {
      "description": "The data type behind a tag definition",
      "type": "string",
      "enum": [
        "ENUM",
        "STRING"
      ]
    },
    "TagType": {
      "description": "Tag types can be introduced dynamically with this type",
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the tag type",
          "$ref": "#/definitions/TagTypeName"
        },
        "type": {
          "description": "The data type behind the tag type",
          "$ref": "#/definitions/TagDataType"
        },
        "values": {
          "description": "A list of possible values, only applicable to the ENUM type",
          "type": "array",
          "items": {
            "$ref": "#/definitions/EnumValue"
          },
          "minItems": 1
        }
      },
      "additionalProperties": false,
      "required": ["name", "type"]
    },
    "Tag": {
      "type": "string"
    },
    "Tagging": {
      "type": "object",
      "properties": {
        "type": {
          "$ref": "#/definitions/TagTypeName"
        },
        "value": {
          "$ref": "#/definitions/Tag"
        }
      },
      "additionalProperties": false,
      "required": ["type", "value"]
    },
    "ComponentPropertyName": {
      "type": "string",
      "pattern": "^[a-z0-9][a-zA-Z0-9]*$"
    },
    "ComponentProperty": {
      "description": "A component property must be either a reference to another component or a value specification",
      "properties": {
        "of": {
          "$ref": "#/definitions/ComposableReference"
        },
        "group": {
          "$ref": "#/definitions/ComposableGroupOptions"
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Tagging"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "of"
      ]
    },
    "ComposableGroupOptions": {
      "type": "object",
      "properties": {
        "min": {
          "type": "integer",
          "minimum": 0
        }
      }
    },
    "Component": {
      "description": "A reusable set of properties. A component may extend other components with additional properties.",
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the component",
          "$ref": "#/definitions/ComposableName"
        },
        "description": {
          "description": "A description of the component",
          "type": "string"
        },
        "extends": {
          "type": "string",
          "description": "A reference to a base component that this component extends",
          "$ref": "#/definitions/ComposableName"
        },
        "properties": {
          "type": "object",
          "description": "An object defining the properties of the component",
          "additionalProperties": {
            "$ref": "#/definitions/ComponentProperty"
          },
          "propertyNames": {
            "$ref": "#/definitions/ComponentPropertyName"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "properties"
      ]
    }
  },
  "type": "object",
  "properties": {
    "components": {
      "description": "A list to define components",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Component"
      }
    },
    "valueTypes": {
      "description": "A list to define value types",
      "type": "array",
      "items": {
        "$ref": "#/definitions/ValueType"
      }
    },
    "tagTypes": {
      "description": "A list to define types of tags",
      "type": "array",
      "items": {
        "$ref": "#/definitions/TagType"
      }
    }
  }
}
```

generated code with additionalProperties set to strict

```kt


class Schema(
    private val cg_map: Map<String, Any?>
) : Map<String, Any?> by cg_map {

    init {
        if (cg_map.containsKey("components"))
            require(cg_map["components"] is List<*>) { "components is not the correct type, expecting List<Component>?" }
            (cg_map["components"] as List<*>).forEach { cg_0 ->
                require(cg_0 is Component) { "components item is not the correct type, expecting Component" }
            }
        if (cg_map.containsKey("valueTypes"))
            require(cg_map["valueTypes"] is List<*>) { "valueTypes is not the correct type, expecting List<ValueType>?" }
            (cg_map["valueTypes"] as List<*>).forEach { cg_2 ->
                require(cg_2 is ValueType) { "valueTypes item is not the correct type, expecting ValueType" }
            }
        if (cg_map.containsKey("tagTypes"))
            require(cg_map["tagTypes"] is List<*>) { "tagTypes is not the correct type, expecting List<TagType>?" }
            (cg_map["tagTypes"] as List<*>).forEach { cg_5 ->
                require(cg_5 is TagType) { "tagTypes item is not the correct type, expecting TagType" }
            }
    }

    /** A list to define components */
    val components: List<Component>?
        get() = cg_map["components"] as List<Component>?

    /** A list to define value types */
    val valueTypes: List<ValueType>?
        get() = cg_map["valueTypes"] as List<ValueType>?

    /** A list to define types of tags */
    val tagTypes: List<TagType>?
        get() = cg_map["tagTypes"] as List<TagType>?

    override fun toString(): String = "Schema(${cg_map.entries.joinToString { "${it.key}=${it.value}" }})"

    override fun equals(other: Any?): Boolean = this === other || other is Schema && cg_map == other.cg_map

    override fun hashCode(): Int = cg_map.hashCode()

    data class Component(
        /** The name of the component */
        val name: String,
        /** A description of the component */
        val description: String? = null,
        /** A reference to a base component that this component extends */
        val extends: String? = null,
        /** An object defining the properties of the component */
        val properties: Properties
    ) {

        init {
            require(cg_regex0.containsMatchIn(name)) { "name does not match pattern $cg_regex0 - $name" }
            if (extends != null)
                require(cg_regex0.containsMatchIn(extends)) { "extends does not match pattern $cg_regex0 - $extends" }
        }

    }

    /**
     * An object defining the properties of the component
     */
    class Properties(
        private val cg_map: Map<String, ComponentProperty>
    ) : Map<String, ComponentProperty> by cg_map {

        override fun toString(): String = "Properties(${cg_map.entries.joinToString { "${it.key}=${it.value}" }})"

        override fun equals(other: Any?): Boolean = this === other || other is Properties && cg_map == other.cg_map

        override fun hashCode(): Int = cg_map.hashCode()

    }

    data class ComponentProperty(
        val of: ComposableReference,
        val group: ComposableGroupOptions? = null,
        val tags: List<Tagging>? = null
    )

    data class ComposableReference(
        val name: String,
        val type: ComposableType
    ) {

        init {
            require(cg_regex0.containsMatchIn(name)) { "name does not match pattern $cg_regex0 - $name" }
        }

    }

    enum class ComposableType {
        COMPONENT,
        VALUE
    }

    class ComposableGroupOptions(
        private val cg_map: Map<String, Any?>
    ) : Map<String, Any?> by cg_map {

        init {
            if (cg_map.containsKey("min")) {
                require(cg_map["min"] is Long) { "min is not the correct type, expecting Long?" }
                (cg_map["min"] as Long).let { min ->
                    require(min >= 0L) { "min < minimum 0 - $min" }
                }
            }
        }

        val min: Long?
            get() = cg_map["min"] as Long?

        override fun toString(): String = "ComposableGroupOptions(${cg_map.entries.joinToString { "${it.key}=${it.value}" }})"

        override fun equals(other: Any?): Boolean = this === other || other is ComposableGroupOptions && cg_map == other.cg_map

        override fun hashCode(): Int = cg_map.hashCode()

    }

    data class Tagging(
        val type: String,
        val value: String
    ) {

        init {
            require(cg_regex0.containsMatchIn(type)) { "type does not match pattern $cg_regex0 - $type" }
        }

    }

    data class ValueType(
        /** The name of the value type */
        val name: String,
        /** The description of the value specification */
        val description: String? = null,
        /** The type of the value specification */
        val type: ValueDataType,
        /** A list of possible values, only applicable to the ENUM type */
        val values: List<String>? = null,
        /** An optional list of units applicable to this value specification */
        val units: List<String>? = null
    ) {

        init {
            require(cg_regex0.containsMatchIn(name)) { "name does not match pattern $cg_regex0 - $name" }
            if (values != null) {
                for (cg_3 in values)
                    require(cg_3.isNotEmpty()) { "values item length < minimum 1 - ${cg_3.length}" }
                require(values.isNotEmpty()) { "values length < minimum 1 - ${values.size}" }
            }
            if (units != null) {
                for (cg_4 in units)
                    require(cg_4.isNotEmpty()) { "units item length < minimum 1 - ${cg_4.length}" }
                require(units.isNotEmpty()) { "units length < minimum 1 - ${units.size}" }
            }
        }

    }

    /**
     * The type of the value specification
     */
    enum class ValueDataType {
        BOOLEAN,
        COMPLEX,
        ENUM,
        NUMBER,
        STRING
    }

    data class TagType(
        /** The name of the tag type */
        val name: String,
        /** The data type behind the tag type */
        val type: TagDataType,
        /** A list of possible values, only applicable to the ENUM type */
        val values: List<String>? = null
    ) {

        init {
            require(cg_regex0.containsMatchIn(name)) { "name does not match pattern $cg_regex0 - $name" }
            if (values != null) {
                for (cg_6 in values)
                    require(cg_6.isNotEmpty()) { "values item length < minimum 1 - ${cg_6.length}" }
                require(values.isNotEmpty()) { "values length < minimum 1 - ${values.size}" }
            }
        }

    }

    /**
     * The data type behind the tag type
     */
    enum class TagDataType {
        ENUM,
        STRING
    }

    companion object {
        private val cg_regex0 = Regex("^[A-Z0-9][A-Za-z0-9]*\$")
    }

}
```

example json causing the issue:

```json
{
  "$schema": "../schema/schema.json",
  "valueTypes": [
    {
      "name": "BasisWeight",
      "type": "NUMBER",
      "units": [
        "g/m²"
      ]
    }
}
```


> there is no "optional" keyword in JSON Schema (it was in a very early version, but it was removed long ago); the fact that the property name is not in a required array is sufficient for it to be considered optional

yes. at this time i was just best-guessing. its removed meanwhile.

**Comment by thedanielhanke** [comment]
while copy pasting code from comments is fun, i`d still rather create a small demo project for easier inspection ;)

**Comment by pwall567** [comment]
Hi Daniel, thanks for creating the demo project, but the comprehensive information dump you provided was sufficient to diagnose the problem.

There is a bug in the template used when `additionalPropertiesOption: strict` is specified.  This is relatively recently added code, and I'm relieved to find that the bug hasn't been around for a long time.

It shouldn't take long to fix – I'll let you know when I have a new version for you.

-Peter

**Comment by thedanielhanke** [comment]
Hey Peter,

that sounds great, thanks a lot.

**Comment by pwall567** [comment]
OK, version 0.109 includes the fix for this issue.  It still uses `json-kotlin-schema` version 0.48; there's still some work to do to switch to the `kjson-core` library, and I didn't want the bug fix to be delayed by that.

I haven't updated the Gradle and Maven plugins to the new version yet.  I should be able to find time to do them tomorrow.

-Peter

**Comment by thedanielhanke** [comment]
Thanks a lot, Peter! :)
